<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resumes [
<!ELEMENT resumes (resume+)>
<!ELEMENT resume (summary?,identification,education?,experience?,skills)>
<!ATTLIST resume rID ID #REQUIRED>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT identification (name,DOB,citizenship,address,telephone,email)>
<!ELEMENT name (forename,surname,honorific+,title*)>
<!ELEMENT forename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT honorific (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>
<!ELEMENT citizenship (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT education (degree*)>
<!ELEMENT degree (degreeName,institution,major+,minor*,honours?,period)>
<!ATTLIST degree level (certificate|undergraduate|professional|masters|doctoral) #REQUIRED>
<!ELEMENT degreeName (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT honours EMPTY>
<!ELEMENT experience (position*)>
<!ELEMENT position (title+,description?,period)>
<!ATTLIST position where CDATA #REQUIRED>
<!ELEMENT period (startDate,endDate)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT skills (skill*)>
<!ELEMENT skill EMPTY>
<!ATTLIST skill what (SQL|Scheme|Python|R|LaTeX) #REQUIRED>
<!ATTLIST skill level (1|2|3|4|5) #REQUIRED>
]>
<resumes>

  <resume rID="r01">
    <summary>
      I am Amber's resume!
    </summary>
    <identification>
      <name>
        <forename>
          Amber
        </forename>
        <surname>
          Zhu
        </surname>
        <honorific>
          Student
        </honorific>
        <title>
          My title is student...
        </title>
      </name>
      <citizenship>
        Chinese
      </citizenship>
      <address>
        University avenue
      </address>
      <telephone>
        4160000000
      </telephone>
      <email>
        amberqianyizhu@outlook.com
      </email>
    </identification>
    <education>
      <degree level="undergraduate">
        <degreeName>
          Bachelor of science
        </degreeName>
        <institution>
          SQL Programmer
        </institution>
        <major>
          Accounting
        </major>
        <honours>
        </honours>
        <period>
          2018
        </period>
      </degree>
    </education>
    <experience>
      <position where="markham">
        <title>
          General accounting clerk
        </title>
        <description>
          Im ambers decription
        </description>
        <period>
          <startDate>
            2017
          </startDate>
          <endDate>
            2018
          </endDate>
        </period>
      </position>
    </experience>
    <skills>
      <skill what="SQL" level="3"/>
      <skill what="Python" level="5"/>
    </skills>
  </resume>

  <resume rID="r02">
    <summary>
      I am Ian's resume!
    </summary>
    <identification>
      <name>
        <forename>
          Ian
        </forename>
        <surname>
          Zheng
        </surname>
        <honorific>
          Student
        </honorific>
        <title>
          My title is student...
        </title>
      </name>
      <citizenship>
        Chinese
      </citizenship>
      <address>
        BA
      </address>
      <telephone>
        4260000000
      </telephone>
      <email>
        xiabiande@outlook.com
      </email>
    </identification>
    <education>
      <degree level="undergraduate">
        <degreeName>
          Bachelor of science
        </degreeName>
        <institution>
          SQL Programmer
        </institution>
        <major>
          Accounting
        </major>
        <honours>
        </honours>
        <period>
          2018
        </period>
      </degree>
    </education>
    <experience>
      <position where="markham">
        <title>
          General accounting clerk
        </title>
        <description>
          Im ambers decription
        </description>
        <period>
          <startDate>
            2017
          </startDate>
          <endDate>
            2018
          </endDate>
        </period>
      </position>
    </experience>
    <skills>
      <skill what="SQL" level="3"/>
      <skill what="Python" level="5"/>
      <skill what="R" level="5"/>
      <skill what="Scheme" level="3"/>
      <skill what="LaTex" level="3"/>
    </skills>
  </resume>
</resumes>
