<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE postings [
<!ELEMENT postings (posting+)>
<!ELEMENT posting (position,reqSkill+,questions*)>
<!ATTLIST posting pID ID #REQUIRED>
<!ELEMENT position (#PCDATA)>
<!ELEMENT reqSkill EMPTY>
<!ATTLIST reqSkill what (SQL|Scheme|Python|R|LaTeX) #REQUIRED>
<!ATTLIST reqSkill level (1|2|3|4|5) #REQUIRED>
<!ATTLIST reqSkill importance (1|2|3|4|5) #REQUIRED>
<!ELEMENT questions (question*)>
<!ELEMENT question (#PCDATA)>
<!ATTLIST question qID CDATA #REQUIRED>
]>

<postings>
  <posting pID="1">
    <position>
      SQL Programmer
    </position>
    <reqSkill what="SQL" level="3" importance="5"/>
    <reqSkill what="SQL" level="5" importance="3"/>
    <questions>
      <question qID="100">
        question100
      </question>
    </questions>
  </posting>

  <posting pID="2">
    <position>
      LaTeX Programmer
    </position>
    <reqSkill what="SQL" level="2" importance="3"/>
    <reqSkill what="Latex" level="3" importance="1"/>
    <questions>
      <question qID="200">
        question200
      </question>
      <question qID="300">
        question300
      </question>
    </questions>
  </posting>

  <posting pID="3">
    <position>
      R Programmer
    </position>
    <reqSkill what="R" level="5" importance="1"/>
    <reqSkill what="Latex" level="3" importance="5"/>
  </posting>
</postings>
